data:
  raw: data2/raw/sample.csv
  processed: data2/processed/cleanAnomaly.csv
  final: data2/final/final.csv

pipeline:
  pipeline1: models/iforest_pipeline


hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

